# Hexo site configuration

title: My Personal Blog
subtitle: 记录技术、学习、项目和生活思考
description: 记录技术、学习、项目和生活思考的个人博客
keywords:
  - 技术博客
  - Next.js
  - Hexo
  - Markdown
author: Alex
language: zh-CN
timezone: Asia/Shanghai

url: https://demo-1-vercel-2-3-4.vercel.app
permalink: posts/:title/
pretty_urls:
  trailing_index: false
  trailing_html: false

source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang

new_post_name: :title.md
default_layout: post
titlecase: false
external_link:
  enable: true
  field: site
  exclude: ""
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
syntax_highlighter: highlight.js
highlight:
  line_number: true
  auto_detect: false
  tab_replace: ""
  wrap: true
  hljs: false

index_generator:
  path: ""
  per_page: 8
  order_by: -date

default_category: 技术
category_map:
tag_map:

meta_generator: true
date_format: YYYY-MM-DD
time_format: HH:mm
updated_option: mtime

per_page: 8
pagination_dir: page

theme: butterfly

feed:
  type: atom
  path: atom.xml
  limit: 20
  hub:
  content: true
  content_limit: 140
  content_limit_delim: " "
  order_by: -date

sitemap:
  path: sitemap.xml

search:
  path: local-search.xml
  field: post
  content: true
  format: html

deploy:
  type: ""
